apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-toxiccomment
  name: toxiccomment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-toxiccomment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-toxiccomment
    spec:
      containers:
      - image: mdavis29/datascience_example:toxiccomment
        name: toxiccomment
        ports:
        - containerPort: 5000
